# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nflow.proto\x12\x12virtual_circuit.v1\"\xb4\x01\n\x04\x46low\x12\x19\n\x0cingress_port\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x1a\n\rsource_vlanid\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x18\n\x0b\x65gress_port\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x18\n\x0b\x64\x65st_vlanid\x18\x04 \x01(\rH\x03\x88\x01\x01\x42\x0f\n\r_ingress_portB\x10\n\x0e_source_vlanidB\x0e\n\x0c_egress_portB\x0e\n\x0c_dest_vlanidb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOW']._serialized_start=35
  _globals['_FLOW']._serialized_end=215
# @@protoc_insertion_point(module_scope)
