# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service/virtual_circuit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service/virtual_circuit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dservice/virtual_circuit.proto\x12\x12virtual_circuit.v1\"L\n\x0cSetUpRequest\x12\x11\n\ta_side_id\x18\x01 \x01(\x04\x12\x11\n\tb_side_id\x18\x02 \x01(\x04\x12\x16\n\x0e\x62\x61ndwidth_kbps\x18\x03 \x01(\x04\"#\n\rSetUpResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\"$\n\x0fTearDownRequest\x12\x11\n\ta_side_id\x18\x01 \x01(\x04\"&\n\x10TearDownResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x32\xb5\x01\n\x0eVirtualCircuit\x12L\n\x05SetUp\x12 .virtual_circuit.v1.SetUpRequest\x1a!.virtual_circuit.v1.SetUpResponse\x12U\n\x08TearDown\x12#.virtual_circuit.v1.TearDownRequest\x1a$.virtual_circuit.v1.TearDownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service.virtual_circuit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETUPREQUEST']._serialized_start=53
  _globals['_SETUPREQUEST']._serialized_end=129
  _globals['_SETUPRESPONSE']._serialized_start=131
  _globals['_SETUPRESPONSE']._serialized_end=166
  _globals['_TEARDOWNREQUEST']._serialized_start=168
  _globals['_TEARDOWNREQUEST']._serialized_end=204
  _globals['_TEARDOWNRESPONSE']._serialized_start=206
  _globals['_TEARDOWNRESPONSE']._serialized_end=244
  _globals['_VIRTUALCIRCUIT']._serialized_start=247
  _globals['_VIRTUALCIRCUIT']._serialized_end=428
# @@protoc_insertion_point(module_scope)
