# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry_report.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry_report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import service.flow_pb2 as flow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16telemetry_report.proto\x12\x12virtual_circuit.v1\x1a\nflow.proto\"j\n\x0fTelemetryReport\x12)\n\x07\x66low_id\x18\x01 \x01(\x0b\x32\x18.virtual_circuit.v1.Flow\x12\x15\n\rrx_byte_count\x18\x02 \x01(\x04\x12\x15\n\rtx_byte_count\x18\x03 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYREPORT']._serialized_start=58
  _globals['_TELEMETRYREPORT']._serialized_end=164
# @@protoc_insertion_point(module_scope)
