# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from service.virtual_circuit import virtual_circuit_pb2 as virtual__circuit__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in virtual_circuit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VirtualCircuitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetUp = channel.unary_unary(
                '/virtual_circuit.v1.VirtualCircuit/SetUp',
                request_serializer=virtual__circuit__pb2.SetUpRequest.SerializeToString,
                response_deserializer=virtual__circuit__pb2.SetUpResponse.FromString,
                _registered_method=True)
        self.TearDown = channel.unary_unary(
                '/virtual_circuit.v1.VirtualCircuit/TearDown',
                request_serializer=virtual__circuit__pb2.TearDownRequest.SerializeToString,
                response_deserializer=virtual__circuit__pb2.TearDownResponse.FromString,
                _registered_method=True)


class VirtualCircuitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TearDown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VirtualCircuitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUp,
                    request_deserializer=virtual__circuit__pb2.SetUpRequest.FromString,
                    response_serializer=virtual__circuit__pb2.SetUpResponse.SerializeToString,
            ),
            'TearDown': grpc.unary_unary_rpc_method_handler(
                    servicer.TearDown,
                    request_deserializer=virtual__circuit__pb2.TearDownRequest.FromString,
                    response_serializer=virtual__circuit__pb2.TearDownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'virtual_circuit.v1.VirtualCircuit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('virtual_circuit.v1.VirtualCircuit', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VirtualCircuit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/virtual_circuit.v1.VirtualCircuit/SetUp',
            virtual__circuit__pb2.SetUpRequest.SerializeToString,
            virtual__circuit__pb2.SetUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TearDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/virtual_circuit.v1.VirtualCircuit/TearDown',
            virtual__circuit__pb2.TearDownRequest.SerializeToString,
            virtual__circuit__pb2.TearDownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
